package Weloveblog::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

=head1 NAME

Weloveblog::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Weloveblog>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Weloveblog::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.48

=head1 AUTHOR

Nitipit Nontasuwan

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
